// 備品リストの初期テンプレート（リアル販促物）。
// 各プロジェクトを初めて開いたときに、この内容を「独立コピー」として作成する。
// 以後はプロジェクトごとに 追加/削除/チェック/数量編集 が可能（シートには依存しない）。

export type SupplyKind = "指定" | "推奨"
export type SupplySeed = { kind: SupplyKind; name: string; url?: string; note?: string; qty?: string }
export type SupplyCatSeed = { key: string; title: string; items: SupplySeed[] }

// Amazon は dp/商品ID の正規URLに整えて登録（長い計測パラメータは除去）
const az = (id: string) => `https://www.amazon.co.jp/dp/${id}`

export const PJT_SUPPLIES_TEMPLATE: SupplyCatSeed[] = [
  {
    key: "A",
    title: "A.入り口受付用品",
    items: [
      { kind: "指定", name: "インカム2個入り", url: "https://x.gd/zdLYD", qty: "3" },
      { kind: "推奨", name: "ラック(受付用)", url: "https://x.gd/5HTtk", qty: "1" },
      { kind: "推奨", name: "レターケース(チラシ用)", url: az("B005F77KUQ"), qty: "1" },
      { kind: "推奨", name: "多色ボールペン(2本入)", url: az("B0DPWK955F"), qty: "3" },
      { kind: "推奨", name: "油性ペン(10本入)", url: az("B00SMOZOWA"), qty: "1" },
      { kind: "指定", name: "スクエアハンディ", url: az("B0FFSNTMGG"), qty: "1" },
      { kind: "指定", name: "スクエアハンディケース", url: az("B0FBZ5YZQD"), qty: "1" },
      { kind: "指定", name: "スクエアハンディ保護フィルム", url: az("B0FX7P4R5N"), qty: "1" },
      { kind: "指定", name: "スクエアターミナル", url: az("B0FY5Y2CW9"), qty: "1" },
      { kind: "推奨", name: "レシート(20巻)", url: "https://x.gd/gR2n3", qty: "1" },
      { kind: "推奨", name: "ドロワー", url: az("B0DXVTZ19C"), qty: "1" },
      { kind: "推奨", name: "受付ポーチ", url: az("B0F4D9K8K8"), qty: "2" },
      { kind: "推奨", name: "3尺脚立", url: az("B06XWQDV3Y"), qty: "2" },
      { kind: "推奨", name: "マグネット(2枚入)", url: az("B0GYBN914H"), qty: "5" },
      { kind: "推奨", name: "養生テープ(10本入)", url: az("B01HIJICLO"), qty: "1" },
      { kind: "推奨", name: "雨具(4着入)", url: az("B0DRJDL7RJ"), qty: "1" },
    ],
  },
  {
    key: "B",
    title: "B.拭き上げスペース&タオル関連",
    items: [
      { kind: "指定", name: "各種拭き上げタオルBOX", url: az("B0BSLBHSX9"), qty: "4" },
      { kind: "指定", name: "雨用タオルボックス", url: az("B0C7NYKSLZ"), qty: "1" },
      { kind: "指定", name: "使用済みタオル入れ", url: az("B08DXWS6FQ"), qty: "1" },
      { kind: "推奨", name: "タオル回収かご", url: az("B0CGV6Z7VF"), qty: "4" },
      { kind: "指定", name: "ラック", url: az("B01LWP8AL2"), qty: "2" },
      { kind: "指定", name: "ボディー用クロス(400枚)", note: "カワゾン", qty: "3" },
      { kind: "推奨", name: "内装用クロス(20枚)", url: "https://www.monotaro.com/p/1848/1365/", qty: "10" },
      { kind: "推奨", name: "ホイール用クロス(20枚)", url: "https://www.monotaro.com/p/1848/1347/", qty: "10" },
      { kind: "指定", name: "掃除機", url: az("B00421KG4I"), qty: "3" },
      { kind: "指定", name: "フィルター替え(3枚)", url: az("B005HN0V18"), qty: "2" },
      { kind: "指定", name: "掃除機の収納", url: az("B0FQNCKGRR"), qty: "2" },
      { kind: "指定", name: "掃除機用コードリール", url: az("B0099ZE1VQ"), qty: "3" },
      { kind: "推奨", name: "タイヤWAXスプレーボトル(2個)", url: az("B0G5BHJB5Q"), qty: "1" },
      { kind: "推奨", name: "タイヤWAXスポンジ", url: az("B0CMC782DW"), qty: "2" },
      { kind: "推奨", name: "手洗い場石鹸", url: az("B07NLKSWHB"), qty: "2" },
      { kind: "推奨", name: "ゴミ箱", url: az("B0D3L1QJ16"), qty: "1" },
      { kind: "推奨", name: "2尺脚立", url: az("B06XW896H7"), qty: "3" },
      { kind: "推奨", name: "洗濯機", url: az("B0CP7LDC9M"), qty: "1" },
      { kind: "推奨", name: "洗濯機給水用ホース等", url: az("B001CDCYNU"), qty: "1" },
      { kind: "推奨", name: "洗剤", url: az("B07VV4F1H9"), qty: "1" },
    ],
  },
  {
    key: "C",
    title: "C.洗車機清掃＆メンテナンス工具",
    items: [
      { kind: "推奨", name: "6尺脚立", url: az("B0BH82NVK6"), qty: "2" },
      { kind: "推奨", name: "デッキブラシ", url: az("B0DJSF7PH9"), qty: "2" },
      { kind: "推奨", name: "水切りワイパー", url: az("B01HJM3X4Q"), qty: "2" },
      { kind: "推奨", name: "液剤用カート", url: az("B00C6Q11Y0"), qty: "1" },
      { kind: "推奨", name: "グリスガン", url: az("B0GGYDSGCH"), qty: "2" },
      { kind: "推奨", name: "リチウムグリス", url: az("B00UYG4QRI"), qty: "4" },
      { kind: "推奨", name: "ニトリル(Mサイズ)", url: az("B09KGT8K2P"), qty: "1" },
      { kind: "推奨", name: "バール", url: az("B0050A7MMO"), qty: "1" },
      { kind: "推奨", name: "バケツ(2個)", url: az("B07ZQ3SYB8"), qty: "1" },
      { kind: "指定", name: "ガラコ(2個)", url: "https://x.gd/OByD9", qty: "1" },
      { kind: "推奨", name: "ケルヒャー", url: az("B014D0T2G0"), qty: "1" },
      { kind: "推奨", name: "ホースリール(20m)", url: az("B07N87C5V5"), qty: "1" },
      { kind: "推奨", name: "泥すくい用スコップ", url: az("B091CFBDQY"), qty: "1" },
      { kind: "推奨", name: "ショップタオル2個入り", url: az("B00KIIF3V0"), qty: "2" },
      { kind: "指定", name: "スクレイパー", url: az("B0DPLS85H3"), qty: "2" },
      { kind: "指定", name: "替え刃(100枚入)", url: az("B0CSC64LWN"), qty: "1" },
      { kind: "推奨", name: "たわし(72個入)", url: az("B01D8J52NO"), qty: "1" },
      { kind: "推奨", name: "土のう袋(50枚入)", url: az("B08J9V9L4L"), qty: "1" },
      { kind: "推奨", name: "どの太郎", url: az("B07ND5QNH5"), qty: "1" },
      { kind: "推奨", name: "三角コーン", url: az("B0F79C6H3S"), qty: "10" },
      { kind: "指定", name: "針金セット", url: az("B0BD2333TC"), qty: "1" },
      { kind: "推奨", name: "コードリール", url: az("B002P8W9DG"), qty: "1" },
      { kind: "推奨", name: "メガネセット", url: az("B08N62R6S2"), qty: "1" },
      { kind: "推奨", name: "スパナセット", url: az("B00IRSIUR2"), qty: "1" },
      { kind: "推奨", name: "インパクトドライバー", url: az("B09RPL4D5C"), qty: "1" },
      { kind: "推奨", name: "インパクト用ソケット", url: az("B00GLLUNOK"), qty: "1" },
      { kind: "推奨", name: "六角レンチセット", url: az("B07XGZMK14"), qty: "1" },
      { kind: "推奨", name: "プラス・マイナスドライバー", url: az("B08L8QNKMM"), qty: "2" },
      { kind: "推奨", name: "ハンマー", url: az("B09NBJC1T8"), qty: "1" },
      { kind: "推奨", name: "ゴムハンマー", url: az("B00264ODX8"), qty: "1" },
      { kind: "推奨", name: "モンキーレンチ", url: az("B08CK7255P"), qty: "2" },
      { kind: "推奨", name: "チェーンカッター", url: az("B00CBD07MA"), qty: "1" },
      { kind: "推奨", name: "ペンチ", url: az("B006JZBFQI"), qty: "2" },
      { kind: "推奨", name: "ニッパー", url: az("B08ZCHYGN7"), qty: "1" },
      { kind: "推奨", name: "パイレン", url: az("B006JZBV7G"), qty: "2" },
      { kind: "推奨", name: "ラチェットセット", url: "https://x.gd/mGz5K", qty: "1" },
      { kind: "推奨", name: "電圧測定器", url: az("B07JFMGL64"), qty: "1" },
      { kind: "指定", name: "RO測定器", url: az("B0B15H8FYT"), qty: "1" },
      { kind: "推奨", name: "結束バンド", url: az("B000THQ4ZO"), qty: "1" },
      { kind: "推奨", name: "ビニールテープ(5巻)", url: az("B000TGFH5S"), qty: "1" },
      { kind: "推奨", name: "工具ケース", url: az("B002A5S5WI"), qty: "1" },
    ],
  },
  {
    key: "D",
    title: "D.トレーラーハウス内・設備関連",
    items: [
      { kind: "指定", name: "パソコン", url: az("B0F333JB5Q"), qty: "1" },
      { kind: "推奨", name: "マウス", url: az("B0956X785M"), qty: "1" },
      { kind: "推奨", name: "コピー機", url: az("B0CTQ4JMZ3"), qty: "1" },
      { kind: "推奨", name: "コピー用紙(A4)", url: az("B07SFSWVVC"), qty: "1" },
      { kind: "推奨", name: "コピー用紙(A3)", url: az("B07SFDMKSC"), qty: "1" },
      { kind: "推奨", name: "ラベルプリンター", url: az("B01IG8IP7W"), qty: "1" },
      { kind: "推奨", name: "ラベルシール(10個)", url: az("B0987XNZ12"), qty: "20" },
      { kind: "推奨", name: "ラミネート", url: az("B07ZB5HWXC"), qty: "1" },
      { kind: "推奨", name: "ラミネートフィルムA4(100枚)", url: az("B0BF9VWSKN"), qty: "1" },
      { kind: "推奨", name: "ラミネートフィルムA3(100枚)", url: az("B0BF9X73L8"), qty: "1" },
      { kind: "推奨", name: "店舗スマホ", url: az("B08R841VB1"), qty: "1" },
      { kind: "推奨", name: "アイフォンフィルム", url: az("B085GR9HCZ"), qty: "1" },
      { kind: "推奨", name: "アイフォンケース", url: az("B08MPLBQNC"), qty: "1" },
      { kind: "推奨", name: "アイフォン充電器", url: az("B0CH8H52T5"), qty: "1" },
      { kind: "推奨", name: "充電ケーブル(タイプC)", url: az("B0H1M2LRFS"), qty: "1" },
      { kind: "推奨", name: "充電器本体(タイプC)", url: az("B0FWJK8GV9"), qty: "2" },
      { kind: "推奨", name: "延長コード(2m)", url: az("B0877666H6"), qty: "2" },
      { kind: "推奨", name: "Wi-Fi（光回線）", url: "https://fixedcost.moneyforward.com/internet/", qty: "-" },
      { kind: "指定", name: "Wi-Fi ルーター", url: az("B0DDXYJG4W"), qty: "1" },
      { kind: "推奨", name: "電子レンジ", url: az("B09Q881CTN"), qty: "1" },
      { kind: "推奨", name: "冷蔵庫", url: az("B09M6SKBHC"), qty: "1" },
      { kind: "推奨", name: "ポット", url: az("B0G62RT8X5"), qty: "1" },
      { kind: "推奨", name: "時計", url: az("B07PXWTYWL"), qty: "1" },
      { kind: "推奨", name: "オフィスデスク", url: az("B0FT7M793Q"), qty: "1" },
      { kind: "推奨", name: "オフィスチェア", url: az("B078X9TB2F"), qty: "4" },
      { kind: "推奨", name: "メイン棚", url: az("B004AC05F4"), qty: "1" },
      { kind: "推奨", name: "スタッフ荷物置き", url: "https://x.gd/4Fzz8", qty: "1" },
      { kind: "推奨", name: "ハンガーラック", url: az("B00KSVZGIM"), qty: "1" },
      { kind: "推奨", name: "ハンガー(10個)", url: az("B0CTZNRG82"), qty: "1" },
      { kind: "推奨", name: "金庫", url: az("B0CQSS16GL"), qty: "1" },
      { kind: "推奨", name: "現金ポーチ", url: az("B0CLCRS978"), qty: "1" },
      { kind: "推奨", name: "コインカウンター", url: "https://x.gd/og4ER", qty: "1" },
      { kind: "推奨", name: "会員証保管ケース", url: "https://x.gd/wFlBD", qty: "2" },
      { kind: "推奨", name: "ホワイトボード＆ペン", url: "https://x.gd/gO8Lt", qty: "1" },
      { kind: "推奨", name: "A4ファイル", url: az("B0G3PFCG61"), qty: "1" },
      { kind: "推奨", name: "レターケース(チラシ用)", url: az("B005F77KUQ"), qty: "1" },
      { kind: "推奨", name: "メモ帳", url: az("B00JO1IFLW"), qty: "1" },
      { kind: "推奨", name: "両面テープ", url: az("B09V359T81"), qty: "2" },
      { kind: "推奨", name: "ハサミ", url: az("B01BRGUAT6"), qty: "1" },
      { kind: "推奨", name: "カッター", url: az("B001D3ARIS"), qty: "2" },
      { kind: "推奨", name: "画鋲", url: "https://www.amazon.co.jp/s?k=%E7%94%BB%E9%8B%B2", qty: "1" },
      { kind: "推奨", name: "洗車パス用クリップ(100個)", url: az("B07RC5HL7W"), qty: "10" },
      { kind: "推奨", name: "ほうきちりとり", url: az("B002161R6M"), qty: "1" },
      { kind: "推奨", name: "ゴミ箱", url: az("B071YD7YMK"), qty: "2" },
      { kind: "推奨", name: "手洗い石鹸", url: az("B07NLKSWHB"), qty: "3" },
      { kind: "推奨", name: "ティッシュ", url: az("B0CPLCZ27T"), qty: "1" },
      { kind: "推奨", name: "トイレットペーパー", url: az("B07WCSL63X"), qty: "2" },
      { kind: "推奨", name: "ウェットティッシュ", url: "https://x.gd/7O6Gy", qty: "1" },
      { kind: "推奨", name: "フェイスタオル(5枚)", url: az("B076V74526"), qty: "1" },
      { kind: "推奨", name: "トイレクリーナー", url: az("B0F1YHMLBY"), qty: "2" },
      { kind: "推奨", name: "トイレ清掃ブラシ", url: az("B0D9LFSCKP"), qty: "2" },
      { kind: "推奨", name: "トイレ棚", url: az("B00RCGMEWW"), qty: "2" },
      { kind: "推奨", name: "トイレゴミ箱", url: az("B07P9PSDBD"), qty: "2" },
      { kind: "推奨", name: "トイレポット(女性用)", url: az("B07KGJW51J"), qty: "1" },
      { kind: "推奨", name: "トイレゴミ袋", url: az("B00L1ZRT6G"), qty: "1" },
      { kind: "推奨", name: "ペーパータオル(12個)", url: az("B0CPLNTR5C"), qty: "1" },
    ],
  },
]
